// This file was autogenerated by DataExtractor
using System;
namespace AnvilPacker.Level {
    public partial class BlockMaterial {
        const MaterialAttributes BM = MaterialAttributes.BlocksMotion;
        const MaterialAttributes F = MaterialAttributes.Flammable;
        const MaterialAttributes L = MaterialAttributes.Liquid;
        const MaterialAttributes SB = MaterialAttributes.SolidBlocking;
        const MaterialAttributes R = MaterialAttributes.Replaceable;
        const MaterialAttributes S = MaterialAttributes.Solid;

        public static BlockMaterial Air              { get; } = Reg("air", R);
        public static BlockMaterial StructureVoid    { get; } = Reg("structure_void", R);
        public static BlockMaterial Portal           { get; } = Reg("portal", 0);
        public static BlockMaterial Carpet           { get; } = Reg("carpet", F);
        public static BlockMaterial Plant            { get; } = Reg("plant", 0);
        public static BlockMaterial UnderwaterPlant  { get; } = Reg("underwater_plant", 0);
        public static BlockMaterial ReplaceablePlant { get; } = Reg("replaceable_plant", F | R);
        public static BlockMaterial NetherShoots     { get; } = Reg("nether_shoots", R);
        public static BlockMaterial ReplaceableUnderwaterPlant { get; } = Reg("replaceable_underwater_plant", R);
        public static BlockMaterial Water            { get; } = Reg("water", L | R);
        public static BlockMaterial BubbleColumn     { get; } = Reg("bubble_column", L | R);
        public static BlockMaterial Lava             { get; } = Reg("lava", L | R);
        public static BlockMaterial SnowLayer        { get; } = Reg("snow_layer", R);
        public static BlockMaterial Fire             { get; } = Reg("fire", R);
        public static BlockMaterial Supported        { get; } = Reg("supported", 0);
        public static BlockMaterial Cobweb           { get; } = Reg("cobweb", S);
        public static BlockMaterial RedstoneLamp     { get; } = Reg("redstone_lamp", BM | SB | S);
        public static BlockMaterial OrganicProduct   { get; } = Reg("organic_product", BM | SB | S);
        public static BlockMaterial Soil             { get; } = Reg("soil", BM | SB | S);
        public static BlockMaterial SolidOrganic     { get; } = Reg("solid_organic", BM | SB | S);
        public static BlockMaterial DenseIce         { get; } = Reg("dense_ice", BM | SB | S);
        public static BlockMaterial Aggregate        { get; } = Reg("aggregate", BM | SB | S);
        public static BlockMaterial Sponge           { get; } = Reg("sponge", BM | SB | S);
        public static BlockMaterial ShulkerBox       { get; } = Reg("shulker_box", BM | SB | S);
        public static BlockMaterial Wood             { get; } = Reg("wood", BM | F | SB | S);
        public static BlockMaterial NetherWood       { get; } = Reg("nether_wood", BM | SB | S);
        public static BlockMaterial BambooSapling    { get; } = Reg("bamboo_sapling", F | SB | S);
        public static BlockMaterial Bamboo           { get; } = Reg("bamboo", BM | F | SB | S);
        public static BlockMaterial Wool             { get; } = Reg("wool", BM | F | SB | S);
        public static BlockMaterial Tnt              { get; } = Reg("tnt", BM | F | S);
        public static BlockMaterial Leaves           { get; } = Reg("leaves", BM | F | S);
        public static BlockMaterial Glass            { get; } = Reg("glass", BM | S);
        public static BlockMaterial Ice              { get; } = Reg("ice", BM | S);
        public static BlockMaterial Cactus           { get; } = Reg("cactus", BM | S);
        public static BlockMaterial Stone            { get; } = Reg("stone", BM | SB | S);
        public static BlockMaterial Metal            { get; } = Reg("metal", BM | SB | S);
        public static BlockMaterial SnowBlock        { get; } = Reg("snow_block", BM | SB | S);
        public static BlockMaterial RepairStation    { get; } = Reg("repair_station", BM | SB | S);
        public static BlockMaterial Barrier          { get; } = Reg("barrier", BM | SB | S);
        public static BlockMaterial Piston           { get; } = Reg("piston", BM | SB | S);
        public static BlockMaterial UnusedPlant      { get; } = Reg("unused_plant", BM | SB | S);
        public static BlockMaterial Gourd            { get; } = Reg("gourd", BM | SB | S);
        public static BlockMaterial Egg              { get; } = Reg("egg", BM | SB | S);
        public static BlockMaterial Cake             { get; } = Reg("cake", BM | SB | S);

        static BlockMaterial()
        {
            //this will be called after all properties get initialized
            Registry.Freeze();
        }
    }
}
