name: .NET CI

on:
  push:
    branches: [ main ]
    paths: [ 'src/**']
  pull_request:
    branches: [ main ]
    paths: [ 'src/**']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true

    - name: Build and Test
      run: dotnet test -c Debug --verbosity normal