name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true

    - name: Build binaries
      run: |
        for rt in "win-x64" "linux-x64" "osx-x64"; do
          ver=${GITHUB_REF#refs/*/v}
          fn="AnvilPacker-$ver-$rt"
          
          dotnet publish src/AnvilPacker -c Release --self-contained -r $rt -o dist/$fn -p:VersionPrefix=$ver -p:InformationalVersion=$ver-${GITHUB_SHA::8} 
          cd dist/ && zip -r -5 $fn.zip $fn && cd ../
        done

    - name: Upload binaries
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        files: 'dist/*.zip'